spring:
  application:
    name: Notification

  datasource:
    url: jdbc:postgresql://localhost:5432/ilerijava
    username: devuser
    password: devuserpassword
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

server:
  port: 8004

other:
  service:
    user:
      http://192.168.137.195:8007

    order:
      http://192.168.137.169:8003

    gateway:
      http://192.168.137.149:8001

    payment:
      http://192.168.137.52:8006

    product:
      http://192.168.137.35:8002

    invoice:
      http://192.168.137.140:8008

    cart:
      http://192.168.137.244:8005

    shipment:
      http://192.168.137.179:8011